### ISSUE TITLE
GND pin should be squared one, probably.

### ISSUE THREAD

**Issue by azhizhinov** [CarlFabian/gurt-portable#1]
Hello.
Sorry.
It's not a huge problem, but GND pin should be squared, as I know.
Have a nice day.
![2022-10-12_09-24-32](https://user-images.githubusercontent.com/13044908/195266623-01da4236-7281-4a26-a309-23dd20e2864e.png)

**Comment by CarlFabian** [comment]
Thanks for pointing that out! Fixed now
